{{--<select size="1" name="countries_id" >--}}
    <option value="0">select Country</option>
    <option value="94">Afghanistan</option>
    <option value="95">Albania</option>
    <option value="2">Algeria</option>
    <option value="96">American Samoa</option>
    <option value="97">Andorra</option>
    <option value="98">Angola</option>
    <option value="99">Anguilla</option>
    <option value="100">Antartica</option>
    <option value="101">Antigua and Barbuda</option>
    <option value="3">Argentina</option>
    <option value="102">Armenia</option>
    <option value="103">Aruba</option>
    <option value="4">Australia</option>
    <option value="5">Austria</option>
    <option value="104">Bahamas</option>
    <option value="6">Bahrain</option>
    <option value="7">Bangladesh</option>
    <option value="105">Barbados</option>
    <option value="106">Belarus</option>
    <option value="8">Belgium</option>
    <option value="107">Belize</option>
    <option value="108">Benin</option>
    <option value="109">Bermuda</option>
    <option value="110">Bhutan</option>
    <option value="111">Bolivia</option>
    <option value="112">Bosnia and Herzegowina</option>
    <option value="113">Botswana</option>
    <option value="114">Bouvet Island</option>
    <option value="9">Brazil</option>
    <option value="115">British Indian Ocean Territory</option>
    <option value="248">British Virgin Islands</option>
    <option value="116">Brunei Darussalam</option>
    <option value="10">Bulgaria</option>
    <option value="117">Burkina Faso</option>
    <option value="118">Burundi</option>
    <option value="11">Byelorussia</option>
    <option value="119">Cambodia</option>
    <option value="120">Cameroon</option>
    <option value="12">Canada</option>
    <option value="121">Cape Verde</option>
    <option value="122">Cayman Islands</option>
    <option value="123">Central African Republic</option>
    <option value="124">Chad</option>
    <option value="13">Chile</option>
    <option value="14">China</option>
    <option value="125">Christmas Island</option>
    <option value="126">Cocos (Keeling) Islands</option>
    <option value="88">Colombia</option>
    <option value="127">Comoros</option>
    <option value="128">Congo</option>
    <option value="129">Cook Islands</option>
    <option value="15">Costa Rica</option>
    <option value="130">Cote d'Ivoire</option>
    <option value="16">Croatia</option>
    <option value="17">Cuba</option>
    <option value="131">Cyprus</option>
    <option value="18">Czech Republic</option>
    <option value="166">Democratic People's Republic of Korea</option>
    <option value="21">Denmark</option>
    <option value="132">Djibouti</option>
    <option value="133">East Timor</option>
    <option value="134">Ecuador</option>
    <option value="22">Egypt</option>
    <option value="23">Eire</option>
    <option value="135">El Salvador</option>
    <option value="136">Equatorial Guinea</option>
    <option value="137">Eritrea</option>
    <option value="138">Estonia</option>
    <option value="139">Ethiopia</option>
    <option value="140">Falkland Islands</option>
    <option value="141">Faroe Islands</option>
    <option value="187">Federated States of Micronesia</option>
    <option value="142">Fiji</option>
    <option value="24">Finland</option>
    <option value="25">France</option>
    <option value="143">French Guiana</option>
    <option value="144">French Polynesia</option>
    <option value="145">French Southern Territories</option>
    <option value="146">Gabon</option>
    <option value="147">Gambia</option>
    <option value="26">Georgia</option>
    <option value="27">Germany</option>
    <option value="148">Ghana</option>
    <option value="149">Gibraltar</option>
    <option value="28">Greece</option>
    <option value="150">Greenland</option>
    <option value="151">Grenada</option>
    <option value="152">Guadeloupe</option>
    <option value="153">Guatemala</option>
    <option value="154">Guinea</option>
    <option value="155">Guinea-Bissau</option>
    <option value="156">Guyana</option>
    <option value="157">Haiti</option>
    <option value="158">Heard and Mc Donald Islands</option>
    <option value="159">Honduras</option>
    <option value="30">Hong Kong</option>
    <option value="31">Hungary</option>
    <option value="32">India</option>
    <option value="33">Indonesia</option>
    <option value="34">Iran</option>
    <option value="162">Iraq</option>
    <option value="35">Ireland</option>
    <option value="161">Island</option>
    <option value="36">Israel</option>
    <option value="37">Italy</option>
    <option value="163">Jamaica</option>
    <option value="38">Japan</option>
    <option value="39">Jordan</option>
    <option value="164">Kazakhstan</option>
    <option value="40">Kenya</option>
    <option value="165">Kiribati</option>
    <option value="41">Korea</option>
    <option value="42">Kuwait</option>
    <option value="167">Kyrgyzstan</option>
    <option value="168">Lao People's Democratic Republic</option>
    <option value="169">Latvia</option>
    <option value="170">Lebanon</option>
    <option value="171">Lesotho</option>
    <option value="172">Liberia</option>
    <option value="43">Libya</option>
    <option value="173">Liechtenstein</option>
    <option value="44">Lithuania</option>
    <option value="174">Luxembourg</option>
    <option value="175">Macau</option>
    <option value="176">Macedonia</option>
    <option value="177">Madagascar</option>
    <option value="255">Madeira</option>
    <option value="178">Malawi</option>
    <option value="46">Malaysia</option>
    <option value="179">Maldives</option>
    <option value="180">Mali</option>
    <option value="181">Malta</option>
    <option value="182">Marshall Islands</option>
    <option value="183">Martinique</option>
    <option value="184">Mauritania</option>
    <option value="185">Mauritius</option>
    <option value="186">Mayotte</option>
    <option value="47">Mexico</option>
    <option value="188">Moldova</option>
    <option value="189">Monaco</option>
    <option value="190">Mongolia</option>
    <option value="191">Monserrat</option>
    <option value="48">Morocco</option>
    <option value="193">Mozambique</option>
    <option value="194">Myanmar</option>
    <option value="195">Namibia</option>
    <option value="196">Nauru</option>
    <option value="197">Nepal</option>
    <option value="198">Netherlands Antilles</option>
    <option value="199">New Caledonia</option>
    <option value="49">New Zealand</option>
    <option value="200">Nicaragua</option>
    <option value="201">Niger</option>
    <option value="50">Nigeria</option>
    <option value="202">Niue</option>
    <option value="203">Norfolk Island</option>
    <option value="204">Northern Mariana Islands</option>
    <option value="51">Norway</option>
    <option value="205">Oman</option>
    <option value="53">Pakistan</option>
    <option value="206">Palau</option>
    <option value="207">Panama</option>
    <option value="208">Papua New Guinea</option>
    <option value="209">Paraguay</option>
    <option value="86">Peru</option>
    <option value="54">Philippines</option>
    <option value="192">Pitcairn</option>
    <option value="55">Poland</option>
    <option value="56">Portugal</option>
    <option value="210">Puerto Rico</option>
    <option value="57">Qatar</option>
    <option value="211">Reunion</option>
    <option value="58">Romania</option>
    <option value="60">Russian Federation</option>
    <option value="212">Rwanda</option>
    <option value="213">Saint Kitts and Nevis</option>
    <option value="214">Saint Lucia</option>
    <option value="215">Saint Vincent and the Grenadines</option>
    <option value="216">Samoa</option>
    <option value="217">San Marino</option>
    <option value="218">Sao Tome and Principe</option>
    <option value="61">Saudi Arabia</option>
    <option value="62">Scotland</option>
    <option value="219">Senegal</option>
    <option value="220">Seychelles</option>
    <option value="221">Sierra Leone</option>
    <option value="63">Singapore</option>
    <option value="223">Slovakia</option>
    <option value="91">Slovenia</option>
    <option value="222">Solomon Islands</option>
    <option value="224">Somalia</option>
    <option value="64">South Africa</option>
    <option value="65">South Australia</option>
    <option value="66">South Korea</option>
    <option value="67">Spain</option>
    <option value="68">Sri Lanka</option>
    <option value="225">St. Helena</option>
    <option value="226">St. Pierre and Miquelon</option>
    <option value="227">Sudan</option>
    <option value="228">Suriname</option>
    <option value="229">Svalbard and Jan Mayen Islands</option>
    <option value="230">Swaziland</option>
    <option value="69">Sweden</option>
    <option value="70">Switzerland</option>
    <option value="231">Syrian Arab Republic</option>
    <option value="71">Taiwan</option>
    <option value="232">Tajikistan</option>
    <option value="233">Tanzania</option>
    <option value="93">Thailand</option>
    <option value="72">The Netherlands</option>
    <option value="234">Togo</option>
    <option value="235">Tokelau</option>
    <option value="236">Tonga</option>
    <option value="237">Trinidad and Tobago</option>
    <option value="238">Tunisia</option>
    <option value="73">Turkey</option>
    <option value="239">Turkmenistan</option>
    <option value="240">Turks and Caicos Islands</option>
    <option value="241">Tuvalu</option>
    <option value="242">Uganda</option>
    <option value="77">UK</option>
    <option value="87">Ukraine</option>
    <option value="1">Undefined</option>
    <option value="78">United Arab Emirates</option>
    <option value="92">United Kingdom</option>
    <option value="243">Uruguay</option>
    <option value="249">US Virgin Islands</option>
    <option value="79">USA</option>
    <option value="244">Usbekistan</option>
    <option value="80">USSR</option>
    <option value="245">Vanuatu</option>
    <option value="246">Vatican City State</option>
    <option value="81">Venezuela</option>
    <option value="247">Viet Nam</option>
    <option value="82">Wales</option>
    <option value="250">Wallis and Futuna Islands</option>
    <option value="83">Western Australia</option>
    <option value="251">Western Sahara</option>
    <option value="252">Yemen</option>
    <option value="84">Yugoslavia</option>
    <option value="253">Zaire</option>
    <option value="254">Zambia</option>
    <option value="85">Zimbabwe</option>
{{--</select>--}}