<?php
session_start();
include_once('jrnl_subs.php');
$logged_in=is_loggedin();
?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="Generator" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>JCSE Volume 2 Paper 30</title>
<meta name="Template" content="D:\Program Files\Microsoft Office\Templates\extabs_template.dot">
</head>

<body stylesrc="../../default.htm">

<font size="2">
<p><img border="0" src="../../images/jrnl_logo.gif" width="1200" height="84"></p>
</font>
<blockquote>
  <p><small><b>(at http://www.jcse.org/, ISSN 1466-8858)</b></small></p>
  <h2>Volume 2 Paper 30</h2>
  <p>Submitted 13<sup>th</sup> September 1999</p>
  <hr align="RIGHT">
  <h2>Characterization of the Electrochemical Events at Intrinsic Breakdown
  Sites on Organically Coated AA2024-T3</h2>
  <i>
  <p>A.M. Mierisch and S.R. Taylor</p>
  </i>
  <p>Center for Electrochemical Science and Engineering, University of Virginia<br>
  Charlottesville, VA 22903</p>
  <h3>Abstract</h3>
  <p>An understanding of the events leading to the local breakdown of
  organically coated alloys requires the use of local electrochemical and
  chemical methods. Intrinsic (i.e. naturally occuring) breakdown events on
  AA2024-T3 coated with a series of neat resins (vinyl, polyurethane, and epoxy)
  were examined using Local Electrochemical Impedance Mapping/Spectroscopy (LEIM/S)
  along with supportive techniques. Several revealing events and processes were
  identified. Several types of breakdown sites were identified that differed in
  both electrochemical and underfilm chemistry characteristics. The time
  evolution of these defects was observed as a rise in the local impedance in
  the firtst stages of observation. Metastable behavior defects have also been
  observed. Present effort is focussed on theoretical corroboration of the
  interpretation of these events.</p>
  <h3>Introduction</h3>
  <p>The initial sites of corrosion on organically coated alloy substrates are <strike>most</strike>
  likely governed by either chemical heterogeneities within the organic coating
  [1], hetero-geneities within the alloy (e.g. intermetallics) [2,3], or a
  juxtaposition of the two, assuming a physically uniform film. An understanding
  of the relative contributions from these processes to coating relies on the
  ability to obtain information on the local chemical and electrochemical. It is
  well cited in the literature [1,4,5] that corrosion of coated alloys occurs
  locally.</p>
  <p>Traditionally, the electrochemical investigation of organic coating
  behavior has used global techniques to provide insight into the general
  performance of a coating [6-11]. However, these measurements are averaged over
  the entire surface and do not provide information about individual sites of
  corrosion initiation. It is believed that information about these sites will
  help govern the development of better surface pre-treatment and coating
  chemistries. Thus, recent efforts have turned towards developing methods that
  can measure the important electrochemical events at these breakdown sites
  [12-17].</p>
  <p>This paper presents several observations of local electrochemical events
  associated with the breakdown of intrinsic defects (i.e. naturally occurring)
  on organically coated AA2024-T3 using Local Electrochemical Impedance Mapping
  (LEIM) and Spectroscopy (LEIM) in conjunction with other supportive methods.
  The literal translation of these data provide insight into the initiation and
  evolution processes of localized underfilm corrosion.</p>
  <b>
  <h3>Experimental Methods</h3>
  </b>
  <p>The LEIM/S system used in this investigation employed the five-electrode
  (split micro-reference electrode) configuration originally designed by Lillard,
  Isaacs, and Moran [15], and further developed for specific use on local
  defects in coated alloys [17] as described in detail by Mierisch [16]. The
  probe uses a 5-electrode configuration with two teflon coated Ag/AgCl
  micro-reference electrodes, each 125<font face="Symbol">m</font> m in
  diameter, in addition to the standard working, counter and reference
  electrodes. In mapping, a single, small amplitude (ca. 15 mV) sine wave
  perturbation of optimal frequency (generally 700 Hz) is applied to a DC
  potential set at the global open circuit potential of the substrate. The local
  current density is measured by measuring the potential gradient in solution
  above the substrate between the two micro-reference electrodes and then
  converting this potential difference through Ohm�s law to a local current
  density. The local impedance (or admitance) is determined by comparing the
  global voltage to the local current density, and an LEI map is generated by
  moving the probe to discrete sites across the sample and plotting the local
  admittance as a function of x,y position.. LEI spectroscopy operates by
  holding the probe over a particular x,y position and scanning the sne wave
  excitation frequency, generally between 10KHz and 1Hz. In both cases the
  voltage signal from the split micro-reference electrode is amplified to
  minimize the required excitation signal and maintain a nondestructive
  character.</p>
  <p>All electrochemical measurements were performed on 1 mm thick AA2024-T3 cut
  into 6.5 x 6.5 cm panels coated with a neat organic resin. One of several
  coating chemistries were applied depending on the particular variable to be
  studied. These coatings were (a) vinyl VYHH copolymer of polyvinyl chloride
  and polyvinyl acetate, (b) polyurethane coatings made with either a 100%
  polyether polyurethane or a polyurethane composed of 50% polyether and 50%
  polyester (both mixed with isocyanate, a dibutyl tin dilaurate catalyst and
  methyl ethyl ketone solvent), (c) a two-part polyester polyurethane comprised
  of Desmophen polyester polyol and desmodur aliphatic polyisocyanate, and (d) a
  two-part epoxy comprised of bisphenol A-epichlorohydrin-based epoxy resin
  solution with an Epi-cure fatty acid-polyethylenepolyamine based polyamide
  mixture curing agent. Butyl cellosolve, in varying amounts, was used as a
  solvent to adjust viscosity in coatings (c) and (d).</p>
  <p>All panels were cleaned prior to coating by the following procedure and
  then left to air dry: scrubbed with acetone, scrubbed with Alconox, cleaned
  ultrasonically in hexanes for at least 5 minutes, then rinsed with isopropanol.
  Ultrapure water was used for rinsing between steps. The appropriate coating
  was then spin cast onto the substrate producing a uniform dried film thickness
  of 5-20 microns depending on the experiment. Freshly coated samples were dried
  in a dessicator for at least 48 hours prior to use. A glass reservoir was
  affixed at its base perimeter to the coating surface with RTV silicone.
  Samples were exposed primarily to 0.6 M NaCl of ambient aeration, but other
  solutions including 0.1 M NaCl and 0.1 M KCl were used as needed.</p>
  <b>
  <h3>Results and Discussion</h3>
  </b>
  <h4>Types of Defects</h4>
  <p>An important observation made in early investigations [16] was that several
  different types of defects occurred within a single panel. These defects types
  were diferentiated initially by the color that they attained upon long-term
  exposure. Two such defects were classified as &quot;red&quot; and
  &quot;black&quot; blisters. LEIM was used on examples of such blisters in
  order to evaluate the electrochemical differences between them. Maps of a red
  and black blister are shown in Figure 1.</p>
  <p><img src="{{ $htmURL }}v2p30f1large.gif" width="821" height="392"></p>
  <p><b>Figure 1: LEIM plots showing the differences in electrochemical activity
  between black (left) and red (right) blisters. Note the higher electrochemical
  activity of the red blister. These AA2024-T3 panels were coated with vinyl
  VYHH to 10<font face="Symbol">m</font> m thickness and exposed to 0.6 NaCl.</b></p>
  <p>It should be noted that these types of blister (i.e. red and black) were
  observed on all samples when exposed to chloride solutions regardless of the
  coating chemistry, however differences in rate of formation, and extent may
  vary. It is clear from the figure that the red blister is electrochemically
  more active, while the black blister is relatively passive. After several
  weeks, the coating was removed from the substrate and the alloy surface at the
  blister sites examined by an optical microscope. As suspected from the LEIM
  results,</p>
  <p>the red blister had indeed incurred significant metal loss, whereas the
  black blister had caused little damage. An example of the pitting caused by a
  red blister is shown in an electron micrograph in Figure 2.</p>
  <p><img src="{{ $htmURL }}v2p30f2large.gif" width="617" height="512"></p>
  <p><b>Figure 2: Electron micrograph of a pitted region of the substrate
  beneath the initiation site of a red blister.. This substrate had previously
  been coated with a 10<font face="Symbol">m</font> m thick polyester
  polyurethane coating. The coating was removed for viewing in the electron
  microscope.</b></p>
  <p>It was hypothesized that LEIM/S could predict which initial defects might
  become the severe red blisters or the more innocuous black blisters by
  comparison of initial electrochemical activity to the eventual blister formed.
  LEIS was performed on defects which were identified through mapping in early,
  still microscopic stages. The results are shown in Figure 3. The defect which
  would later become a red blister was even then significantly more
  electrochemically active than the eventual black blister.</p>
  <p><img src="{{ $htmURL }}v2p30f3large.gif" width="397" height="368"></p>
  <p><b>Figure 3: LEIS shows that even in early stages, the red blister is more
  electrochemically active than the black blister. The smaller circle diameter
  on this Nyquist plot represents a lower pore resistance.</b></p>
  <p>In addition to differences in electrochemical activity, the blisters were
  also examined for chemical differences. In one experiment, small quantities of
  solution were drawn from several examples of each type of blister and the
  ionic content of the underfilm solution was analyzed using capillary
  electrophoresis (CE)[16]. Cu<sup>2+</sup>, Al<sup>3+</sup>, and Mg<sup>2+</sup>
  ions were found in the solution of the red blisters whereas only small amounts
  of Mg<sup>2+</sup> and Zn<sup>2+</sup> were found in the black blister
  solution. The cations present in the red blister solution suggest that active
  dealloying of the substrate or a particular phase within the substrate has
  taken place [2,3,18,19]. These resuts demonstrate that the electrochemical and
  chemical nature within very small (&lt;1 mm) blisters can be quantified and
  characterized.</p>
  <p>Differences in underfilm pH and potential also differentiate these blister
  types and substantiate the LEIM/S findings. In a similar experiment, local pH
  values of the underfilm solutions were obtained for several examples of each
  type of blister. This was done by inserting an Ir/IrO microelectrode into the
  blister. Prior to these tests, the electrochemical activity of each blister
  was mapped by LEIM. Some of the red blisters were found to be low in
  electrochemical activity, while most were found to be high in activity as
  expected. In fact, the blisters which were high in electrochemical activity
  were found to contain solution at pH values of 3-5, whereas the blisters with
  low electrochemical activity, presumably temporarily repassivated, contained
  solution of pH 8-9. Local pH measurement provides valuable information about
  the underfilm solution, but it is also a destructive technique. Once the
  coating has been breached, the defect will no longer develop as it would have.
  However, this problem can be avoided through use of the nondestructive LEIM
  technique.</p>
  <h4>Time Evolution of Defect Sites</h4>
  <p><img src="{{ $htmURL }}v2p30f4large.gif" width="702" height="593"></p>
  <b>
  <p>Figure 4: LEIM of the evolution of a red blister. Note the fluctuation in
  electrochemical activity representative of metastability. At 52 hours, the
  open circuit potential dropped dramatically, suggesting a possibly breach in
  the coating.</p></b>
  <p>The time evolution of electrochemical defect sites was studied in further
  detail. Defects were monitored over time using LEIM to detect changes in
  electrochemical activity. A representative time series of maps for a single
  defect is shown in Figure 4. Red blisters generally show metastable behavior,
  with periods of temporary repassivation or decreased activity occurring
  between periods of increasing electrochemical activity. Such metastable
  behavior has been suggested in the literature [20] but has not been
  specifically investigated. It has been suggested [21] that the biphasic nature
  parallels capacitance changes in the coating. Metastability could also be
  caused by accumulation of corrosion product periodically dispersed by the
  convection of hydrogen evolution. The former possibility will be investigated
  by comparing LEIM of a gold disk electrode with and without a coating.
  Reference standard gold disk electrodes have been created using Si/SiO wafers
  with embedded gold electrodes. These standards will be discussed in a future
  paper.</p>
  <p>In later stages, metastability is visually observable as growth spurts. The
  blisters experience rapid growth (visible growth within 1-2 hours) followed by
  lengthy periods of no outward growth (12-24 hours). In earlier stages,
  however, when these changes are not visually apparent, such a localized event
  can only be measured by local electrochemical methods. The observed changes in
  growth and in pH value of the solution render the possibility unlikely that
  metastability of the blisters might be due to changes in coating properties
  such as water uptake. However, preliminary studies have shown that a low (3-5)
  pH solution increases the rate of transfer of ions across the coating
  interface. It is possible that variations in pH affect the activity of the
  blisters and could contribute to metastability.</p>
  <p>Repassivation, or &quot;healing&quot; has been suggested to occur on
  chromate conversion coated (CCC) aluminum alloys and cited as an asset of
  these coatings [22]. LEIM was used to study the effect of chromate added to
  solution on the activity of red blisters. In Figure 5, LEIM shows the change
  in electrochemical activity before and after chromate solution is added.</p>
  <p><img src="{{ $htmURL }}v2p30f5large.gif" width="848" height="516"></p>
  <p><b>Figure 5: LEIM of a red blister before and after a chromate solution was
  added to the bulk electrolyte. 1.2 M Na<sub>2</sub>CrO<sub>4</sub> was added
  to 0.6 M NaCl. After chromate is added, the admittance decreases, in agreement
  with a rise in open circuit potential. After 24 hours, the admittance begins
  to rise, although open circuit potential alone does not indicate this change.</b></p>
  <p>Once the chromate was added, the open circuit potential rose to a more
  noble value as expected, and LEIM showed a decreased electrochemical activity
  in the blister. LEIS also showed a decrease in electrochemical activity.
  However, while the open circuit potential remained relatively constant
  suggesting a continuing repassivation of the blister, LEIM and LEIS showed
  that, in fact, electrochemical activity began to, again, increase within the
  blister. Future studies will focus on metastability of defects on substrates
  coated first with CCC�s and then with organic coating. Although several
  investigations have studied CCC coated substrates [22-24], the effect of an
  organic coating on CCC coated substrates has not been investigated from a
  local electrochemistry standpoint.</p>
  <h4>Delineation of Anodic and Cathodic Regions</h4>
  <p>In addition to characterizing overall properties of individual blisters,
  LEIM was also used to distinguish between anodic and cathodic regions of red
  blisters. It was observed that blisters initiate at a given site, and then
  branch into one or more secondary lobes that grow away from the initiation
  site. LEIM showed that the initiation site is electrochemically active, while
  the secondary lobes are relatively inactive. An example of this is shown in
  Figure 6.</p>
  <p><img src="{{ $htmURL }}v2p30f6large.gif" width="917" height="507"></p>
  <p><b>Figure 6: An optical micrograph of a red blister with initiation site
  (lighter region to right) and secondary lobe (darker region to left). LEIM
  shows the higher activity in the initiation region. Local underfilm open
  circuit potentials, also shown, confirm the higher activity in the initiation
  region.</b></p>
  <p>Energy dispersive spectroscopy (EDS) also revealed a higher amount of Cu
  and lower amount of Al and Mg in the general area of initiation (with Cu
  deposited just outside the initiation pit region). Local open circuit
  measurements, made with a Ag/AgCl microelectrode similar to the one used in pH
  measurements, showed a more anodic potential within the initiation region and
  a more noble potential in the secondary lobe. Although further studies are
  required to draw an absolute conclusion, it can be presumed that the
  initiation region is the anode and the secondary lobe/lobes the cathode. The
  contributing factors to the blister front advancement are presently under
  investigation.</p>
  <h4>Early Stages of Defect Formation</h4>
  <p>Whereas later stages of blister development can be characterized by
  compiling information obtained both from local electrochemical and chemical
  methods and from optical and global methods, the earliest stages of
  development and initiation of a blister require the use of local
  electrochemical methods. By stepping the LEI probe over the surface of a
  coated alloy panel, LEIM was able to reveal microscopic regions of defect
  initiation. During this early stage of development, it was found that the
  impedance had actually increased relative to the surrounding region. LEIM of
  an example of this is shown in Figure 7.</p>
  <p><img src="{{ $htmURL }}image274.gif" width="466" height="313"><b>&nbsp;</p>
  </b>
  <p><b>Figure 7: An example of the initial decrease in admittance, or increase
  in impedance, in earliest stages of defects. This AA2024-T3 panel was coated
  with vinyl VYHH to 10 <font face="Symbol">m</font> m thickness and exposed to
  0.6 M NaCl solution.</b></p>
  <p>Several explanations for this increase in impedance have been proposed.
  Although it was suspected that nonuniform field distributions emanating from
  the defect may have given rise to the increased impedance, this explanation
  was found to be improbable. The expected field from an equipotential disk was
  derived and calculated for dimensions similar to those in the experiment. It
  was shown that the micro-reference electrodes would have to be very close to
  the surface compared to the radius of the disk ( or size of the disk is large
  relative to the height of the micro-reference electrodes from the surface
  -unlikely in early stages). If the probe were indeed within this realm, a dip
  in admittance would originate from an increased base admittance value and
  substantial peaks from edge effects at the perimeter of the disk would be
  apparent. A representative plot of theoretical results that would result in an
  admittance dip is shown in Figure 8. The normal field over an equipotential
  disk is calculated for different heights above the surface relative to the
  radius of the disk. Actual admittance plots of defects did not display any of
  these features. Two additional explanations for the increased impedance are
  water nucleation under the coating and build-up of corrosion product at the
  initiation site [16].</p>
  <p><img src="{{ $htmURL }}v2p30f8.gif" width="473" height="474"></p>
  <p><b>Figure 8: The normal field is calculated theoretically for an
  equipotential disk at various heights (z) from the surface relative to the
  radius of the disk (a). Note that a dip does occur when the probe is very
  close to the surface, but this dip is accompanied by significant edge effects
  and the dip does not extend below the baseline of the surface.</b></p>
  <h3>Conclusions</h3>
  <p>The local nature of corrosion of coated alloys necessitates the use of
  local electrochemical and chemical techniques toward understanding individual
  breakdown events. LEIM/S is capable of characterizing <i>in situ </i>the
  initiation of and changes in electrochemical activity of a single defect
  without disturbing blister development. LEIM/S of local breakdown sites has
  also confirmed previous observations of can reveal metastable behavior in the
  evolution of coating behavior.</p>
  <p>LEIM has identified several different types of defects on coated AA2024-T3
  with the two most prevalent examples being a red and a black blister. Through
  LEIM and LEIS the red blister was found to be more electrochemically active
  both in early and later stages of development than the black blister. The
  blisters were further characterized by CE and it was found that the underfilm
  solution of the red blisters contained Cu<sup>2+</sup>, Al<sup>3+</sup>, and
  Mg<sup>2+</sup> ions whereas the black blister only contained small amounts of
  Mg<sup>2+</sup> and Zn<sup>2+</sup> ions. LEIM revealed that red blisters
  often repassivated during development and that this repassivation was found to
  correspond to an increase in local pH from an aggressive environment of 3-5 to
  a more benign environment of 8-9. Red blisters also caused a visibly severe
  amount of damage to the substrate as compared to black blisters.</p>
  <p>The metastable nature of defects on the coated panels was monitored by LEIM.
  Several possible explanations for the metastability, including changes in
  coating properties, accumulation of corrosion product, and variation in local
  pH were discussed. The metastable nature of red blisters caused by the
  addition of chromate to the bulk solution was also examined.</p>
  <p>Red blisters were observed to initiate in a given region and branch into
  secondary lobes. LEIM showed that the initiation sites were anodic to the
  secondary lobes, suggesting a possible cathodic head in growth. Local OCP
  measurements and EDS measurements of the composition of the affected substrate
  confirmed the differentiation of the red blisters into an active initiation
  region with corrosion taking place and relatively passive secondary lobes.</p>
  <p>LEIM revealed an initial increase in impedance of blisters in the earliest
  stages of development. Possible explanations, including nonuniform field
  distribution, water nucleation, and corrosion product accumulation were
  presented. Nonuniform field distributions were found to be an unlikely cause.
  Defects in such early, microscopic stages were located through LEIM of the
  substrate surface.</p>
  <h3>Acknowledgements</h3>
  <p>The authors would like to thank the Air Force Office of Scientific Research
  (AFOSR) for their sponsorship of this project as well as Jingnan Yuan and
  Robert Kelly for their contributions of CE analysis.</p>
  <h3>References</h3>
  <ol>
    <li>J.E.O. Mayne, D.J. Mills, <i>J. Oil Col Chem Assoc.,</i> <b>58</b>:155
      (1975).</li>
    <li>G.S. Chen, M Gao and R.P. Wei, <i>Corrosion</i>, <b>52</b>(1):8 (1996).</li>
    <li>P.Schmutz and G.S. Frankel, <i>J. Electrochem. Soc.,</i> <b>145</b>(7):2295
      (1998).</li>
    <li>R.C. Bacon, J.J. Smith, F.M. Rigg, <i>Ind. Engr. Chem</i>., <b>40</b>(1):161
      (1948).</li>
    <li>J.A. Grandle, S.R. Taylor, <i>Corrosion</i>, <b>50</b>(10):792 (1994).</li>
    <li>H. Leidheiser, Jr., <i>Corrosion</i>, <b>39</b>(5):189 (1983).</li>
    <li>F. Mansfeld, M.W. Kendig, S.Tasi, <i>Corros. Sci.,</i> <b>23</b>(4):317
      (1983).</li>
    <li>S.R. Taylor, <i>IEEE Trans. Elec. Insul.,</i> <b>24</b>(5):787 (1989).</li>
    <li>S. Haruyama, M. Asari, Tsuru, &quot;Corrosion Protection by Organic
      Coatings&quot;, The Electrochemical Society, Proc. 87-2 (1987), p.197.</li>
    <li>S. Hirayama, S. Haruyama, <i>Corrosion,</i> <b>47</b>(12):953 (1991).</li>
    <li>C.T. Chen and B.S. Skerry, <i>Corrosion</i>, <b>47</b>(8):598 (1991).</li>
    <li>I. Annergren, D. Thierry, F. Zou, <i>J. Electrochem. Soc.,</i> <b>144</b>,
      1208 (1997).</li>
    <li>E. Bayet, F. Huet, M. Keddam, K. Ogle, and H. Takenouti, <i>J.
      Electrochem. Soc.,</i> <b>144</b>(4),L87 (1997).</li>
    <li>H. S. Isaacs, Y. Ishikawa, <i>Corrosion 85</i>, paper 55, Nace
      International, Houston, TX (1985).</li>
    <li>R. S. Lillard, P.J. Moran and H.S. Isaacs, <i>J. Electrochem. Soc.,</i> <b>139</b>(4),
      1007 (1992).</li>
    <li>A. M. Mierisch, S.R. Taylor, in <u>Electrochemically Based
      Microstructural Characterization</u>, Vol. 500, Ed. By R.A. Gerhardt, M.A.
      Alim, S.R. Taylor, Materials Rsearch Society, Warrendale, PA, p.35 (1998).</li>
    <li>M. W. Wittman and S.R. Taylor, in <u>Advances in Corrosion Protection by
      Organic Coatings II</u>, Ed. By J.D. Scantlebury and M.W. Kendig, The
      Electrochem. Soc., PV <b>95-13</b>:158-168 (1995).</li>
    <li>R.G. Buchheit, R.P. Grant, P.F. Hlava, B. Mckenzie, G.L. Zender, <i>J.
      Electrochem Soc.,</i> <b>144</b>(8):2621 (1997).</li>
    <li>K. Nisancioglu,<i> J. Electrochem. Soc., </i><b>137</b>(1):69 (1990).</li>
    <li>J.A. Grandle, S.R. Taylor, <i>Corrosion</i>, <b>50</b>(10):792 (1994).</li>
    <li>J.E. Castle, in <u>Advanced Monitoring and Analytical Techniques</u>,
      Ed. By F. Mansfeld, W.H. Smyrl, Proceeding of <i>Corrosion</i>, (1997).</li>
    <li>J. Zhao, G. Frankel, R.L. McCreery, <i>J. Electrochem. Soc</i>., <b>145</b>(7):2258
      (1998).</li>
    <li>G.P. Halada, C.R. Clayton, M.J. Vasquez, J.R. Kearns, M.W. Kendig, S.L.
      Jeanjaquet, G.G. Peterson, G.S. McCarthy, G.L. Carr, in <u>Critical
      Factors in Localized Corrosion III</u>, Electrochemical Society, PV98-17
      (1998).</li>
    <li>A.E. Hughes, R. Taylor, B. Hilton, <i>Surface and Interface Analysis</i>,
      <b>25</b>(4):223 (1997).</li>
  </ol>
  <hr>
  <p><a href="http://www.jcse.org/Background.htm">Comment</a> on this
  paper</p>
  <p>Send Mail to the <script>mailtoeditor()</script></p>
  <p><a href="../../default.php">Journal of Corrosion Science &amp; Engineering
  Home Page</a><br>
  <a href="http://corrosiontest.its.manchester.ac.uk/default.htm">Corrosion Information Server</a><br>
  <a href="http://minerva.acc.virginia.edu/~cese">Centre for Electrochemical
  Science and Engineering, University of Virginia (JCSE Mirror Site)</a></p>
  <p>&nbsp;</p>
</blockquote>

</body>

</html>
