<h2>JCSE Volume 6 Paper 46</h2>

<div align=center>

<hr size=2 width="100%" align=center>

</div>

<h2>Effect of Magnetic Fields on Corrosion</h2>

<p>Y. C. Tang, M. Gonzalez-Torreira, S. Yang, A. J. Davenport</p>

<p>Metallurgy and Materials, School of Engineering, The University
 of Birmingham, Edgbaston, Birmingham B15 2TT, UK. <script>mailto2('a.davenport','bham.ac.uk')</script>

<h3>Abstract</h3>

<p>&sect;1 The effect of magnetic fields on corrosion processes was
investigated.� The Lorenz force was found to cause solution flow for corrosion
of NdFeB magnets under drops of HCl, and copper sheet under drops of nitric
acid when a small magnet was attached to the back of the sheet.� The field
generated by a PrFeB magnet also influenced the morphology of attack by nitric
acid.� In experiments with artificial pits grown by dissolution of wires
encapsulated in epoxy resin, the Lorenz force was observed to affect solution
flow in the bulk electrolyte, but did not influence the current/voltage
characteristics of artificial pits in paramagnetic 304 stainless steel.� The
current/voltage characteristics of ferromagnetic iron and nickel artificial
pits were affected by strong external magnetic fields, which could either
enhance or suppress dissolution depending upon the field orientation.� The
effect was attributable to the attraction of paramagnetic ions to regions of
high field gradient in the vicinity of the electrodes.� </p>

<p>&sect;2 <b>Keywords: </b>magnetic field, artificial pit, mass
transport, corrosion product, magnetic field gradient, Lorenz force.</p>

<h3>Introduction</h3>

<p>&sect;3 It is well known that magnetic fields can affect
electrochemical processes by changing the mass transport of species in solution
[1,2]. Mass transport is an important factor in corrosion processes, so it is of interest to determine the extent to which magnetic fields affect corrosion, particularly of magnetic materials.� A number of studies have found that magnetic fields can either accelerate or inhibit corrosion processes [3-7]. However, the mechanisms involved are not yet fully understood.� They are likely to involve two forces: the Lorenz force and the field gradient force.� </p>

<h4>Lorenz Force</h4>
<p>&sect;4 The effect of the Lorenz force in electrochemical
      systems has been observed by a number of recent researchers [5,8,9]. Its
      effect in a corroding system was noted as early as 1950 [10], when a
      droplet of electrolyte corroding a metal substrate was observed to rotate in
    between the poles of a magnet. </p>
<p>&sect;5 The Lorenz force acts when charge-carrying ions are moving
within a magnetic field. It is the cross product of the current,<b><i> i</i> </b>and
magnetic field, <b>B, </b>as shown in Figure 1. The Lorenz force acts on the ions, which are deflected together with their solvation shells, causing fluid flow. On a disk electrode, current flows radially outwards, Figure 2. The effect of the Lorenz force is therefore to cause rotation of the solution about an axis parallel to the magnetic field.� This is illustrated in Figure 3 for fields parallel and perpendicular to the electrode surface. </p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image013.jpg" width="261" height="103"></p>

<p align=center>&sect;6 <a
name="_Ref45083381">Figure </a>1. Schematic diagram of the Lorenz force.</p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image014.jpg" width="307" height="132"></p>

<p align=center><a name="OLE_LINK1">�(a)����������������������� (b)</a></p>

<p align=center>&sect;7 <a
name="_Ref45088631">Figure </a>2. Schematic diagram of current fluxes flowing
radially outwards, (a) side view and (b) top view, from a disk electrode in an
insulating plane.</p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image015.jpg" width="302" height="112"></p>

<p align=center>(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
(b)</p>

<p align=center>&sect;8 <a
name="_Ref45088656">Figure </a>3. Schematic diagram of the effect of the Lorenz
force on solution flow around a disk electrode (see Figure 2) when a magnetic
field is applied (a) parallel and (b) perpendicular to the electrode surface.</p>

<h4>Field Gradient Force</h4>
<p>&sect;9 In an inhomogeneous magnetic field, paramagnetic
  species are attracted to the region of highest field gradient.� In an
  electrochemical cell, this effect can be observed when a ferromagnetic
  electrode is magnetised in an external magnetic field.� Large field gradients
  are created in the region adjacent to the electrode [11]. The
  effect is illustrated in Figure 4. Leventis <i>et al.</i>[12]
  theoretically proved that in the absence of convection, the field gradient causes
  a drift of paramagnetic species toward areas of higher field.</p>
<p align="center"><img border=0 src="{{ $htmURL }}images/image016.jpg" width="283" height="77"></p>

<p align=center>(a) </p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image017.jpg" width="283" height="80"></p>

<p align=center>�(b) </p>

<p align=center>&sect;10 <a
name="_Ref45088848">Figure </a>4. Schematic diagram of magnetic flux lines for
(a) a ferromagnetic electrode and (b) a paramagnetic electrode in an external
magnetic field. It is assumed that the electrode is a wire with a flat polished
end (disk electrode), and is viewed from the end and from the side.� Regions of
high field gradient are indicated in red.</p>

<h4>Pitting Corrosion and Artificial Pits</h4>
<p>&sect;11  The stability of a localised corrosion site such as
  a pit depends upon maintaining an aggressive acidic environment inside the pit
  cavity that promotes metal dissolution rather than repassivation.� The acidity
  depends upon hydrolysis of metal cations, as illustrated in Figure 5(a) [13-18]. The
  pit will die (repassivate) if metal cations escape from the pit faster than
  they are produced by dissolution within the pit.� Thus pit stability is
  critically dependent on mass transport of ions.</p>
<p align="center"><img border=0 src="{{ $htmURL }}images/image018.jpg" width="554" height="198"></p>

<p align=center>(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
(b) </p>

<p align=center>&sect;12 <a
name="_Ref45088857">Figure </a>5. Schematic of (a) pits on a metal surface and,
(b) 1-D artificial pit.</p>

<p>&sect;13 The effect of mass transport within pits is readily studied
with a 1-D �lead in pencil� artificial pit, Figure 5(b) [13,16,18-20].� This is produced by embedding a wire in epoxy resin, and dissolving it back to produce a cavity that contains the pit solution.</p>

<p>&sect;14 Figure 6 shows the typical current/voltage characteristics of a 1-D artificial pit. The current increases linearly with voltage from <b>A</b> to <b>B</b> as the rate is controlled by the resistance in the pit cavity (Ohm�s
Law). When the rate of production of metal ions is faster than their diffusion
out of the cavity, the region adjacent to the metal-electrolyte interface
becomes supersaturated with metal ions, and a salt film layer is precipitated (<b>C</b>).
There is a high potential drop across the thick layer of salt film and the
curve drops to point <b>D</b> as a result. The thick salt film layer thins to its
equilibrium state leading to a gradual increase in current, which reaches its
steady state at point <b>E</b>. The current is then controlled by mass
transport of metal ions out of the cavity, and is thus independent of
potential; any increase of the potential is accommodated by the thickening of
the salt film. On the reverse sweep, the salt film thins until the point at
which the diffusion-limited current is equal to the ohmically-limited current
for a film-free surface, <b>F</b>, when the salt film is completely dissolved.
In region <b>G</b>, the ohmically-limited dissolution from a salt film-free
surface is reversible. </p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image019.jpg" width="359" height="257"></p>

<p align=center>&sect;15 <a
name="_Ref45088891">Figure </a>6. Current-voltage characteristics of 1-D
artificial pits.</p>

<h3>Experimental Method</h3>

<h4>Lorenz Force Observations </h4>
<p>&sect;16 NdFeB disks, 10 mm in diameter, were corroded with
  a drop of 1&nbsp;M&nbsp;HCl. Samples were used in the magnetised and
  demagnetised states. Similar disks were mounted in epoxy resin, immersed in pH
  8.4 borate buffer solution, and cathodically polarised at -2&nbsp;V(SCE)
  to produce a flow of hydrogen bubbles. 10 mm PrFeB disks, magnetised and
  demagnetised, were mounted in epoxy, and immersed in 1&nbsp;M HNO<sub>3</sub>
  to corrode freely. Copper sheet, 2 mm thick was corroded with droplet of 40%
  HNO<sub>3</sub>.�An external magnetic field was applied by attaching a small
  NdFeB disk magnet at the back of the copper sheet.� In all cases, the samples
  were viewed with a video camera.</p>
<h4>1-D Artificial Pits</h4>
<p>&sect;17 Iron, nickel, and 304 stainless steel wires,
  0.25&nbsp;mm in diameter were embedded in epoxy resin. Each wire was dissolved
  under potentiostatic control in 1&nbsp;M NaCl to create a cavity 1&nbsp;mm
  deep. The depth of the pit was estimated from Faraday�s Law through the total
  charge passed during the dissolution, and the depth was confirmed with an
  optical microscope. </p>
<p>&sect;18 The current/voltage characteristics of the artificial pits
were studied in 1&nbsp;M NaCl with cyclic voltammetry at a sweep rate of 10
mV/s. In order to visualise the flow of Fe<sup>2+</sup> ions in solution, 0.3%
K<sub>3</sub>Fe(CN)<sub>6</sub> was added, which forms Prussian blue on
reacting with ferrous ions. The electrochemical cell was a 1 x 1 cm cuvette. A
magnetic field of 0.35 T was applied with a horseshoe magnet as shown in Figure
7. </p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image020.jpg" width="400" height="219"></p>

<p align=center>&sect;19 <a
name="_Ref45088938">Figure </a>7. Experimental setup for artificial pit measurements.</p>

<h3>Results and Discussion</h3>

<p>&sect;20 NdFeB corroded vigorously in 1&nbsp;M HCl, producing H<sub>2</sub>
bubbles at the metal surface. On demagnetised NdFeB, the H<sub>2</sub> bubbles
flowed towards the surface of the drop, as shown in Video 1. In contrast, on magnetised NdFeB, the H<sub>2</sub> bubbles streamed in a clockwise path in the droplet, as shown in Video 2. On the opposite face of the magnet, the stream of bubbles flows in the opposite (anticlockwise) direction, Video 3.</p>

</div>

<div>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video1.avi">
<img border=0 src="{{ $htmURL }}images/image021.jpg" width="169" height="127"></span></a></p>

<p align=center><a
name="_Ref45089220">Video </a>1</p>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video2.avi">
<img border=0 src="{{ $htmURL }}images/image022.jpg" width="169" height="127"></span></a></p>

<p align=center><a
name="_Ref45089226">Video </a>2</p>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video3.AVI">
<img border=0 src="{{ $htmURL }}images/image023.jpg" width="169" height="127"></span></a></p>

<p align=center><a
name="_Ref45089232">Video </a>3</p>

</div>

<div>

<p align=center>&sect;21 Videos showing the flow of H<sub>2</sub> bubbles produced from corrosion
on Video 1: a demagnetised NdFeB; and Videos 2 and 3, opposite faces of a
magnetised NdFeB disk 10 mm in diameter.</p>

<p>&sect;22 Hydrogen evolution on cathodically-polarised demagnetised
NdFeB is shown in Video 4. In this case, the video camera was pointed horizontally, parallel to the flat surface of the magnet. The bubbles flowed vertically towards the surface of the solution. On magnetised NdFeB, a helical flow of H<sub>2</sub>
bubbles was observed, Video 5.<br clear=all>
</span></p>

</div>
<div>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video4.avi">
<img border=0 src="{{ $htmURL }}images/image024.jpg" width="238" height="179"></span></a></p>

<p align=center><a
name="_Ref45089248">Video </a>4</p>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video5.avi">
<img border=0 src="{{ $htmURL }}images/image025.jpg" width="238" height="179"></span></a></p>

<p align=center><a
name="_Ref45089255">Video </a>5</p>

</div>

<div>

<p align=center>&sect;23 H<sub>2</sub>
evolution on demagnetised NdFeB (Video 4) and magnetised NdFeB (Video 5) when
they were cathodically polarised.</p>

<p>&sect;24 PrFeB disks with the cross-sectional face held vertically
were immersed in 1&nbsp;M&nbsp;HNO<sub>3</sub>.� Vigorous corrosion took place
with generation of bubbles. On the demagnetised sample, bubbles flowed directly
upwards (Video 6), while on the magnetised sample, a rotating flow of bubbles can be seen, and a ring of dark corrosion products can be observed around the periphery of the sample (Video 7). </p>

</div>
<div>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video6.avi">
<img border=0 src="{{ $htmURL }}images/image026.jpg" width="235" height="188"></span></a></p>

<p align=center><a
name="_Ref45089268">Video </a>6</p>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video7.avi">
<img border=0 src="{{ $htmURL }}images/image027.jpg" width="235" height="188"></span></a></p>

<p align=center><a
name="_Ref45089274">Video </a>7</p>

</div>

<div>

<p align=center>&sect;25 Free corroding

demagnetised PrFeB (Video 6) and magnetised PrFeB (Video&nbsp;7) in
1M HNO<sub>3.</sub> Disks are 10 mm in diameter.</p>

<p>&sect;26 Copper also reacts vigorously with HNO<sub>3</sub>. In the
absence of a magnetic field, bubbles flowed directly to the surface (Video 8).� When a small NdFeB magnet was attached to the back of the sheet, the bubbles were observed to flow in a circular path around the periphery of the magnet (Video 9). </p>

</div>

<div>

<p align="center"><a
href="http://www.jcse.org/volume6/paper46/Video/Video8.avi">
<img border=0 src="{{ $htmURL }}images/image028.jpg" width="238" height="179"></span></a></p>

<p align=center><a
name="_Ref45089282">Video </a>8</p>

<p align="center"><a
href="http://www.jcse.org/volume6/paper46/Video/Video9.avi">
<img border=0 src="{{ $htmURL }}images/image029.jpg" width="238" height="179"></span></a></p>

<p align=center><a
name="_Ref45089292">Video </a>9</p>

</div>

<div>

<p align=center>&sect;27 Cu corroding in HNO<sub>3,
</sub>�Video 8 in absence of� magnetic field, and Video 9 in the presence of a
magnetic field </p>

<p>&sect;28 Figure 8 shows the current/voltage characteristics of an Fe artificial pit electrode. The characteristic regions shown in Figure 6 can be observed.� The data from a number of sequential sweeps are shown, indicating very good reproducibility.</p>

<p align=center><img border=0 src="{{ $htmURL }}images/image030.jpg" width="419" height="316"></p>

<p align=center>&sect;29 <a
name="_Ref45089312">Figure </a>8. Current/voltage curves for an Fe artificial
pit (sweep rate 10&nbsp;mVs<sup>-1</sup>).</p>

<p>&sect;30 Figure 9 shows an image of the Fe artificial electrode during
the experiment shown in Figure 8 and Video 10 shows a time-lapse video of one current/voltage cycle. During the cycle, precipitation of the salt film can be observed.� It then thins (D to E in Figure 6), and thickens again as the voltage increases.�� It thins with decreasing voltage on the reverse sweep, and finally disappears (point G on Figure 6).</p>

</div>

<div>

<p align="center"><img border=0 src="{{ $htmURL }}images/image031.jpg" width="299" height="192"></p>

<p align="center">&sect;31 <a name="_Ref45089352">Figure </a>9 Artificial pit
electrode.</p>

<p align="center"><a
href="http://www.jcse.org/volume6/paper46/Video/video10.avi">
<img border=0 src="{{ $htmURL }}images/image032.jpg" width="238" height="201"></span></a></p>

<p align="center">&sect;32 <a name="_Ref45089384">Video </a>10. Salt film
precipitation (time lapse video of one current/voltage cycle lasting 4 mins as
shown in Figure 8).</p>

</div>
<div>

<p>&sect;33 An Fe artificial pit electrode was dissolved at 1&nbsp;V in
1 M NaCl with added K<sub>3</sub>Fe(CN)<sub>6</sub>. In the absence of a
magnetic field, the Prussian blue product streamed downwards due to the
gravity, Video 11. When an external magnetic field of 0.35&nbsp;T was imposed parallel to the wire (perpendicular to the pit surface), a slow vortex flow gradually developed, Video 12. When the field was imposed parallel to the pit surface (perpendicular to the wire), a more rapid vortex flow was observed, Video 13. </p>

</div>

<div>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video11.avi">
<img border=0 src="{{ $htmURL }}images/image033.jpg" width="171" height="128"></span></a></p>

<p align=center><a
name="_Ref45089424">Video </a>11</p>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video12.avi">
<img border=0 src="{{ $htmURL }}images/image034.jpg" width="171" height="128"></span></a></p>

<p align=center><a
name="_Ref45089449">Video </a>12</p>

<p align=center><a
href="http://www.jcse.org/volume6/paper46/Video/Video13.avi">
<img border=0 src="{{ $htmURL }}images/image035.jpg" width="171" height="128"></span></a></p>

<p align=center><a
name="_Ref45089461">Video </a>13<b><br
clear=all>
    </span></b></p>

</div>

<div>

<p align=center>&sect;34 Videos showing flow
of Prussian blue product from an Fe artificial pit. Video 11 shows dissolution
in the absence of a magnetic field. 0.35T magnetic field
parallel to the wire was present in Video 12, and perpendicular to the wire in
Video 13.</p>

<p>&sect;35 The experiment was repeated with a 304 stainless steel
(paramagnetic) artificial pit electrode. Figure 10 shows similar observations in the bulk solution to those for the iron electrode, confirming that the Lorenz force does not depend on the magnetic properties of electrode.</p>

<p align="center">�<img border=0 src="{{ $htmURL }}images/image036.jpg" width="195" height="196"></p>

<p align=center>(a)</p>
<p align=center><img
border=0 src="{{ $htmURL }}images/image037.jpg" width="197" height="194"></p>
<p align=center>(b)</p>
<p align=center>&sect;36 <a
name="_Ref45089499">Figure </a>10. (a) and (b) Flow of Prussian blue product
from 304 stainless steel artificial pits without a magnetic field present
(left) and with a 0.35 T field applied horizontally in the plane of the image
(right).</p>

<p align=center><img
border=0 src="{{ $htmURL }}images/image038.jpg" width="492" height="267"></p>

<div align="center">
  <script>comment(37);</script>
  <a
name="_Ref45089547">Figure </a>11. Current/voltage curves for a horizontal iron
  artificial pit (dissolving surface is vertical); a magnetic field of
  0.35&nbsp;T, parallel to the pit surface (perpendicular to the wire axis), was
  applied for cycles 4-6 and 10-12.
  <script>comment(38);</script>
</div>
<p>Figure 11 shows the current/voltage curves for an Fe artificial pit with its active dissolving surface aligned vertically (wire is horizontal). The first 3 cycles were performed in the absence of a magnetic field. A field of
0.35&nbsp;T was applied just before the start of the 4<sup>th</sup> cycle. For
cycles 4-6 in a magnetic field, the ohmic linear region extended to a higher
potential and the precipitation of salt film was delayed. The limiting current
density during the diffusion-controlled process was enhanced. When the magnetic
field was removed for cycles 7-9, the process reverted to the initial behaviour
shown for cycles 1-3.� The maximum current was enhanced again when the magnetic
field was reapplied for cycles 10-12.</p>

<p>&sect;39 Attempts to observe changes within the cavity on application
of a field revealed that the pit cavities sometimes contain corrosion products
or gas bubbles trapped within the cavity as can be observed in Videos 14-17. In
the absence of a magnetic field, no movement is observed in the interior of the
pit cavity, Video 14. When a magnetic field was applied parallel to the pit surface (perpendicular to the axis of the wire), small fragments of corrosion products could be observed to flow in the cavity close to the dissolving surface.
It is probably this stirring action that causes the effects observed in Figure 11.�<b><br
clear=all>
</span></b></p>

</div>

<div>

<p align="center"><a
href="http://www.jcse.org/volume6/paper46/Video/Video14.avi">
<img border=0 src="{{ $htmURL }}images/image039.jpg" width="238" height="179"></span></a></p>

<p align=center><a
name="_Ref45089588">Video </a>14</p>

<p align="center"><a
href="http://www.jcse.org/volume6/paper46/Video/Video15.avi">
<img border=0 src="{{ $htmURL }}images/image040.jpg" width="238" height="179"></span></a></p>

<p align=center><a
name="_Ref45089769">Video </a>15</p>

</div>

<div>

<p align=center>&sect;40 Video sequence
within the Fe artificial pit cavity (0.25 mm diameter) during
constant-potential dissolution in the absence of a magnetic field, Video 14,
and in the presence of a 0.35 T magnetic field, Video 15.</p>

<p align="center"><a
href="http://www.jcse.org/volume6/paper46/Video/Video16.avi">
<img border=0 src="{{ $htmURL }}images/image041.jpg" width="238" height="179"></span></a></p>

<p align=center>&sect;41 <a
name="_Ref45089645">Video </a>16. Response of corrosion product within an Fe
artificial pit cavity (0.25 mm diameter) when 0.35 T field first applied.</p>

<p>&sect;42 The loops of the very first cycle immediately after the
introduction of magnetic field, marked with an asterisk (*) in Figure 11, are frequently larger than subsequent cycles. Video 16 shows reactions that took place on application of a magnetic field after the artificial pit had been grown for a number of cycles with no magnetic field. The corrosion products that accumulated at the pit cavity
were vigorously disturbed by the application of the magnetic field. This action
created a considerably higher level of agitation than that in a stationary
field and therefore the salt film precipitation was found to be more difficult
after the field was first applied.</p>

<p>&sect;43 The current/voltage curves for a paramagnetic 304 stainless
steel artificial pit were performed with the same magnetic field orientation.
No difference was found when a magnetic field was applied, Figure 12. This suggests that the Lorenz force action found in the bulk solution (Figure 10) is not sufficient to cause changes to the current voltage characteristics.� Instead, it is likely that the field gradient force causes the stirring in the cavity observed for iron (Video 15).</p>

<p align=center><img border=0
src="{{ $htmURL }}../../image042.jpg" width="492" height="266"></p>

<p align=center>&sect;44 <a
name="_Ref45089748">Figure </a>12. Current/voltage curves for a horizontal 304
stainless steel artificial pit (dissolving surface is vertical); a magnetic
field of 0.35&nbsp;T, parallel to the pit surface (perpendicular to the wire
axis), was applied for cycles 3-4 and 7-8.</p>

<p>&sect;45 Figure 13 shows an Fe artificial pit in the same orientation (wire horizontal; dissolving surface vertical).� In this case, the magnetic field was applied parallel to the wire (perpendicular to the dissolving surface). The
salt film precipitation was accelerated and the limiting current suppressed. A
similar experiment was performed on a ferromagnetic nickel wire (Video 17).� Observation of the region close to the dissolving surface showed that on application of the field, corrosion products, presumably paramagnetic, were attracted to the periphery of the wire.� This is the region of
highest field gradient, as shown in Figure 14.� This suggests that the enhanced formation of a salt film and suppression of diffusion in the cavity shown in Figure 13 are caused by the field gradient effect, which attracts the paramagnetic ions and corrosion products to the dissolving surface, (particularly the periphery), enhancing salt film formation and decreasing the rate of
diffusion.</p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image043.jpg" width="492" height="266"></p>

<p align=center>&sect;46 <a
name="_Ref45089788">Figure </a>13. Current/voltage characteristics of an Fe
pit, vertical pit surface (horizontal wire) with a magnetic field applied
parallel to the wire (perpendicular to the pit surface) for cycles 4-6 and
10-12.</p>

</div>
<div>

<p align="center"><a href="http://www.jcse.org/volume6/paper46/Video/Video17.avi">
<img border=0 src="{{ $htmURL }}images/image044.jpg" width="238" height="179"></span></a>

</div>

<div>

<p align=center>&sect;47 Video 17. Ni
artificial pit (0.25 mm diameter), paramagnetic species were attracted to the
highest field gradient region when the magnetic field was first applied.</p>
<p align=center>&nbsp;<script>comment(48);</script><img border="0" src="{{ $htmURL }}images/figure14.jpg" width="697" height="321"></p>

<p align=center>Figure 14. Schematic
diagram showing the field gradient around a paramagnetic wire electrode in an
external magnetic field: high field gradient regions are shown in red.</p>

<p>&sect;49 This was confirmed by removing the wires after the
experiments and observing them with the scanning electron microscope. A wire
that had dissolved in the absence of the field was slightly concave (Figure 15(a)).� When the field was applied perpendicular to the wire (parallel to the dissolving surface), the surface appeared similar (Figure 15(b)).� However, when the field was applied parallel to the wire (perpendicular to the surface), the surface was deeply convex Figure 15(c), supporting the idea that paramagnetic ions and corrosion products had been attracted to the periphery of the wire (the position of highest field gradient), suppressing dissolution.</p>

<p align="center"><img border=0 src="{{ $htmURL }}images/image046.jpg" width="553" height="279"></p>

<p align=center>�(a)��������������������������������� (b)���������������������������������� (c)</p>

<p align=center>&sect;50 <a
name="_Ref45089866">Figure </a>15. Surface of artificial pits (0.25 mm
diameter) after dissolution in (a) no magnetic field, (b) a magnetic field
perpendicular to the wire (parallel to the surface), and (c) a magnetic field
parallel to the wire (perpendicular to the surface). The upper panel shows a
top view and bottom panel shows a side view.</p>

<h3>Conclusions</h3>

<p>&sect;51 The results show that the presence of a magnetic field can
either enhance or suppress corrosion reactions through their effect on mass
transport.� Both the Lorenz force and field gradient effects can play a role,
but relatively large magnetic fields are required.� In the case of artificial
pits, the field gradient effect rather than the Lorenz force was important.�
Thus, effects of this magnitude are unlikely to be observed for real pits where
the local field gradients are likely to be far lower.</p>

<h3>Acknowledgements</h3>

<p>This work is supported by UUK (ORS award for YC Tang) and
the University of Birmingham. The authors would also like to thank the Applied
Alloy Chemistry Group for provision of magnets.� Helpful discussions with Prof
Nick Leventis are gratefully acknowledged.</p>

<h3>References</h3>

<p>1. T. Z. Fahidy, 'Reviews of Applied Electrochemistry 8. Magnetoelectrolysis', <i>Journal
of Applied Electrochemistry</i>, <b>13</b>, 5, pp553-563, (1983).</p>

<p>2. O.
Aaboubi, J. P. Chopart, J. Douglade, A. Olivier, C. Gabrielli and B. Tribollet,
'Magnetic-Field Effects on Mass-Transport', <i>Journal of the Electrochemical
Society</i>, <b>137</b>, 6, pp1796-1804, (1990).</p>

<p>3. A.
Chiba, K. Kawazu, O. Nakano, T. Tamura, S. Yoshihara and E. Sato, 'The Effects
of Magnetic-Fields on the Corrosion of Aluminum Foil in Sodium-Chloride
Solutions', <i>Corrosion Science</i>, <b>36</b>, 3, pp539-543, (1994).</p>

<p>4. I.
Leshev, M. Mitov and T. Peev, 'Magnetic field effect on steel corrosion',
International Corrosion Conference, 2002.</p>

<p>5. R.
Aogaki and M. Asanuma, 'Magnetic Field Effect on Metal Corrosion', 1st
International Symposium on New Magneto-science, 1999.</p>

<p>6. A.
Rucinskiene, G. Bikulcius, L. Gudaviciute and E. Juzeliunas, 'Magnetic field
effect on stainless steel corrosion in FeCl3 solution', <i>Electrochemistry
Communications</i>, <b>4</b>, 1, pp86-91, (2002).</p>

<p>7. K.
Shinohara and R. Aogaki, 'Magnetic field effect on copper corrosion in nitric
acid', <i>Electrochemistry</i>, <b>67</b>, 2, pp126-131, (1999).</p>

<p>8. K. M.
Grant, J. W. Hemmert and H. S. White, 'Magnetic focusing of redox molecules at
ferromagnetic microelectrodes', <i>Electrochemistry Communications</i>, <b>1</b>,
8, pp319-323, (1999).</p>

<p>9. K. M.
Grant, J. W. Hemmert and H. S. White, 'Magnetic field driven convective
transport at inlaid disk microelectrodes - The dependence of flow patterns on
electrode radius', <i>Journal of Electroanalytical Chemistry</i>, <b>500</b>,
1-2, pp95-99, (2001).</p>

<p>10. F.
Blaha, 'Use of a magnetic field in detecting corrosion currents', <i>Nature</i>,
4223, pp607, (1950).</p>

<p>11. M. D.
Pullins, K. M. Grant and H. S. White, 'Microscale confinement of paramagnetic
molecules in magnetic field gradients surrounding ferromagnetic
microelectrodes', <i>Journal of Physical Chemistry B</i>, <b>105</b>, 37,
pp8989-8994, (2001).</p>

<p>12. N.
Leventis and X. R. Gao, 'Magnetohydrodynamic electrochemistry in the field of
Nd-Fe-B magnets. Theory, experiment, and application in self-powered flow
delivery systems', <i>Analytical Chemistry</i>, <b>73</b>, 16, pp3981-3992,
(2001).</p>

<p>13. G. T.
Gaudet, W. T. Mo, T. A. Hatton, J. W. Tester, J. Tilly, H. S. Isaacs and R. C.
Newman, 'Mass-Transfer and Electrochemical Kinetic Interactions in Localized
Pitting Corrosion', <i>AIChE Journal</i>, <b>32</b>, 6, pp949-958, (1986).</p>

<p>14. M.
Kaneko and H. S. Isaacs, 'Effects of molybdenum on the pitting of ferritic- and
austenitic-stainless steels in bromide and chloride solutions', <i>Corrosion
Science</i>, <b>44</b>, 8, pp1825-1834, (2002).</p>

<p>15. M.
Kaneko and H. S. Isaacs, 'Pitting of stainless steel in bromide, chloride and
bromide/chloride solutions', <i>Corrosion Science</i>, <b>42</b>, 1, pp67-78,
(2000).</p>

<p>16. U.
Steinsmo and H. S. Isaacs, 'Dissolution and Repassivation Kinetics of Fe-Cr
Alloys in Pit Solutions .1. Effect of the Surface Salt Layer', <i>Journal of
the Electrochemical Society</i>, <b>140</b>, 3, pp643-653, (1993).</p>

<p>17. G. S.
Frankel, 'Pitting corrosion of metals - A review of the critical factors', <i>Journal
of the Electrochemical Society</i>, <b>145</b>, 6, pp2186-2198, (1998).</p>

<p>18. N. J.
Laycock and R. C. Newman, 'Localised dissolution kinetics, salt films and
pitting potentials', <i>Corrosion Science</i>, <b>39</b>, 10-11, pp1771-1790,
(1997).</p>

<p>19. H. S.
Isaacs, 'The behaviour of resistive layer in the localised corrosion of
stainless steel', <i>Journal of the Electrochemical Society</i>, <b>120</b>,
11, pp1456-1462, (1973).</p>

<p>20. J. W.
Tester and H. S. Isaacs, 'Diffusional effect in simulated localised corrosion',
<i>Journal of the Electrochemical Society</i>, <b>122</b>, 11, pp1438-1445,
(1975).</p>

</div>
</SCRIPT>


